sudo: required

language: minimal

services:
  - docker

env:
  - POSTGRES_IMAGE=postgres:11.6-alpine CLAIR_VERSION=v2.1.6 CLAIR_LOCAL_SCAN_IMAGE=arminc/clair-local-scan

install:
  - docker build -t $CLAIR_LOCAL_SCAN_IMAGE --build-arg VERSION=$CLAIR_VERSION clair

before_script:
  - docker pull $POSTGRES_IMAGE
  - docker run -d --name postgres -e 'PGDATA=/var/lib/postgresql/clair' -e POSTGRES_PASSWORD=password $POSTGRES_IMAGE
  - until docker run --rm -it --link postgres:postgres -e PGPASSWORD=password $POSTGRES_IMAGE pg_isready -U postgres -h postgres; do sleep 1; done
  - docker run -d --name clair --link postgres:postgres $CLAIR_LOCAL_SCAN_IMAGE

script:
  - ./check.sh
  - docker logs clair

after_success:
  - docker stop clair
  - docker stop postgres
  - docker commit postgres lixwlixw/clair-db:$(date +%Y-%m-%d)
  - docker tag lixwlixw/clair-db:$(date +%Y-%m-%d) lixwlixw/clair-db:latest
  - docker images

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  on:
    branch: master
  script:
    docker push lixwlixw/clair-db:$(date +%Y-%m-%d) &&
    docker push lixwlixw/clair-db:latest
